from typing import List, Dict

from .vector_store import query_collection


def retrieve_context(query: str, top_k: int = 3) -> List[Dict]:
    """Retrieve top-k relevant document chunks from ChromaDB for a query."""
    results = query_collection(query, top_k)
    documents = results.get("documents", [[]])[0]
    metadatas = results.get("metadatas", [[]])[0]
    ids = results.get("ids", [[]])[0]

    contexts: List[Dict] = []
    for doc, meta, _id in zip(documents, metadatas, ids):
        contexts.append(
            {
                "id": _id,
                "text": doc,
                "metadata": meta or {},
            }
        )
    return contexts


def generate_answer(query: str, contexts: List[Dict]) -> str:
    """Generate a simple, deterministic answer from retrieved contexts.

    This implementation does not call any external LLM. Instead, it stitches
    together relevant document snippets into a human-readable response.
    """
    if not contexts:
        return (
            "I could not find relevant information in the current Utkrusht "
            f"documentation for your question: '{query}'. "
            "Please try rephrasing or contact Utkrusht support."
        )

    lines = [f"Question: {query}", "", "Based on our internal documentation:"]

    for idx, ctx in enumerate(contexts, start=1):
        snippet = ctx["text"].strip().replace("\n", " ")
        source = ctx["metadata"].get("source", "unknown")
        lines.append(f"{idx}. (source: {source}) {snippet}")

    lines.append("")
    lines.append(
        "This answer was generated by selecting the most relevant documentation "
        "snippets from our ChromaDB vector store; no external language model "
        "was used."
    )

    return "\n".join(lines)
